export const CALCULATION_TYPES = {
    ADD_NEW_FIELDS: 'ADD_NEW_FIELDS',
    ADD_NEW_TABLE: "ADD_NEW_TABLE",
    REMOVE_TABLE_BY_INDEX: "REMOVE_TABLE_BY_INDEX",
    ADD_ACTIVE_VALUES: "ADD_ACTIVE_VALUES",
    INCREASE_TAB_ACCESS: "INCREASE_TAB_ACCESS",
    SELECT_WAREHOUSE: "SELECT_WAREHOUSE"
}